"""change index for utility

Revision ID: ce8ae4ee66c4
Revises: b504b1e4d844
Create Date: 2025-06-02 10:48:49.394992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8ae4ee66c4'
down_revision = 'b504b1e4d844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_categories_group_id', table_name='categories')
    # op.create_index('idx_categories_group_id', 'categories', ['group_id', 'name', 'parent_id'], unique=True)
    # op.drop_index('uq_group_invitations_invitation_code', table_name='group_invitations')
    # op.create_unique_constraint(op.f('uq_group_invitations_invitation_code'), 'group_invitations', ['invitation_code'])
    op.drop_index('ix_utility_readings_user_id', table_name='utility_readings')
    op.create_index(op.f('ix_utility_readings_user_id'), 'utility_readings', ['user_id', 'address_id', 'service_id', 'period', 'tariff_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utility_readings_user_id'), table_name='utility_readings')
    op.create_index('ix_utility_readings_user_id', 'utility_readings', ['user_id', 'address_id', 'service_id', 'period'], unique=True)
    # op.drop_constraint(op.f('uq_group_invitations_invitation_code'), 'group_invitations', type_='unique')
    # op.create_index('uq_group_invitations_invitation_code', 'group_invitations', ['invitation_code'], unique=False)
    # op.drop_index('idx_categories_group_id', table_name='categories')
    # op.create_index('idx_categories_group_id', 'categories', ['group_id'], unique=False)
    # ### end Alembic commands ###
