"""Add currency tracking fields to payments

Revision ID: 4f11710e1a1c
Revises: d54321d0efd3
Create Date: 2025-09-19 21:13:37.550226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f11710e1a1c'
down_revision = 'd54321d0efd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new currency tracking fields to payments table
    op.add_column('payments', sa.Column('amount_original', sa.Float(), nullable=True, comment='Original amount in transaction currency'))
    op.add_column('payments', sa.Column('currency_original', sa.String(length=3), nullable=True, comment='Original transaction currency'))
    op.add_column('payments', sa.Column('exchange_rate', sa.Float(), nullable=True, comment='Exchange rate at transaction time'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove currency tracking fields from payments table
    op.drop_column('payments', 'exchange_rate')
    op.drop_column('payments', 'currency_original')
    op.drop_column('payments', 'amount_original')
    # ### end Alembic commands ###
