"""add new utility fields

Revision ID: 96c17d3db96e
Revises: 09ac01b56e32
Create Date: 2025-06-20 20:58:48.570845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c17d3db96e'
down_revision = '09ac01b56e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_categories_group_id', table_name='categories')
    # op.create_index('idx_categories_group_id', 'categories', ['group_id', 'name', 'parent_id'], unique=True)
    # op.drop_index('uq_group_invitations_invitation_code', table_name='group_invitations')
    # op.create_unique_constraint(op.f('uq_group_invitations_invitation_code'), 'group_invitations', ['invitation_code'])
    op.add_column('utility_readings', sa.Column('calculation_details', sa.Text(), nullable=True, comment='JSON з деталями розрахунку'))
    op.add_column('utility_readings', sa.Column('reading_type', sa.String(length=50), nullable=True, comment='Тип показника (standard, day, night)'))
    # op.drop_index('ix_utility_readings_unique_period_tariff', table_name='utility_readings')
    # op.create_index('ix_utility_readings_unique_period_tariff', 'utility_readings', ['user_id', 'address_id', 'service_id', 'period', 'tariff_id', 'reading_type'], unique=True)
    op.add_column('utility_services', sa.Column('has_shared_meter', sa.Boolean(), nullable=False, comment='Чи має спільний показник для групи тарифів'))
    op.add_column('utility_tariffs', sa.Column('tariff_type', sa.String(length=50), nullable=True, comment='Тип тарифу (consumption, drainage, day, night, etc)'))
    op.add_column('utility_tariffs', sa.Column('group_code', sa.String(length=50), nullable=True, comment="Код групи для об'єднання тарифів"))
    op.add_column('utility_tariffs', sa.Column('calculation_method', sa.String(length=50), nullable=True, comment='Метод розрахунку (standard, percentage, fixed)'))
    op.add_column('utility_tariffs', sa.Column('percentage_of', sa.Float(), nullable=True, comment='Відсоток від основного тарифу (для зливу води)'))
    # op.create_index('idx_tariff_group', 'utility_tariffs', ['service_id', 'group_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_tariff_group', table_name='utility_tariffs')
    op.drop_column('utility_tariffs', 'percentage_of')
    op.drop_column('utility_tariffs', 'calculation_method')
    op.drop_column('utility_tariffs', 'group_code')
    op.drop_column('utility_tariffs', 'tariff_type')
    op.drop_column('utility_services', 'has_shared_meter')
    # op.drop_index('ix_utility_readings_unique_period_tariff', table_name='utility_readings')
    # op.create_index('ix_utility_readings_unique_period_tariff', 'utility_readings', ['user_id', 'address_id', 'service_id', 'period', 'tariff_id'], unique=True)
    op.drop_column('utility_readings', 'reading_type')
    op.drop_column('utility_readings', 'calculation_details')
    # op.drop_constraint(op.f('uq_group_invitations_invitation_code'), 'group_invitations', type_='unique')
    # op.create_index('uq_group_invitations_invitation_code', 'group_invitations', ['invitation_code'], unique=False)
    # op.drop_index('idx_categories_group_id', table_name='categories')
    # op.create_index('idx_categories_group_id', 'categories', ['group_id'], unique=False)
    # ### end Alembic commands ###
