"""add del subscription_fee

Revision ID: d54321d0efd3
Revises: c4db938e23da
Create Date: 2025-06-23 11:10:34.883216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd54321d0efd3'
down_revision = 'c4db938e23da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_categories_group_id', table_name='categories')
    # op.create_index('idx_categories_group_id', 'categories', ['group_id', 'name', 'parent_id'], unique=True)
    # op.drop_index('uq_group_invitations_invitation_code', table_name='group_invitations')
    # op.create_unique_constraint(op.f('uq_group_invitations_invitation_code'), 'group_invitations', ['invitation_code'])
    # op.drop_index('ix_utility_readings_unique_period_tariff', table_name='utility_readings')
    # op.create_index('ix_utility_readings_unique_period_tariff', 'utility_readings', ['user_id', 'address_id', 'service_id', 'period', 'tariff_id', 'reading_type'], unique=True)
    op.alter_column('utility_tariffs', 'tariff_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='Тип тарифу (consumption, drainage, day, night, subscription)',
               existing_comment='Тип тарифу (consumption, drainage, day, night, etc)',
               existing_nullable=True)
    # op.create_index('idx_tariff_group', 'utility_tariffs', ['service_id', 'group_code'], unique=False)
    op.drop_column('utility_tariffs', 'subscription_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utility_tariffs', sa.Column('subscription_fee', mysql.FLOAT(), nullable=True, comment='Абонентська плата'))
    # op.drop_index('idx_tariff_group', table_name='utility_tariffs')
    op.alter_column('utility_tariffs', 'tariff_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='Тип тарифу (consumption, drainage, day, night, etc)',
               existing_comment='Тип тарифу (consumption, drainage, day, night, subscription)',
               existing_nullable=True)
    # op.drop_index('ix_utility_readings_unique_period_tariff', table_name='utility_readings')
    # op.create_index('ix_utility_readings_unique_period_tariff', 'utility_readings', ['user_id', 'address_id', 'service_id', 'period', 'tariff_id'], unique=True)
    # op.drop_constraint(op.f('uq_group_invitations_invitation_code'), 'group_invitations', type_='unique')
    # op.create_index('uq_group_invitations_invitation_code', 'group_invitations', ['invitation_code'], unique=False)
    # op.drop_index('idx_categories_group_id', table_name='categories')
    # op.create_index('idx_categories_group_id', 'categories', ['group_id'], unique=False)
    # ### end Alembic commands ###
