"""Add subscription_fee to utility_tariffs

Revision ID: b504b1e4d844
Revises: b29d05e24af7
Create Date: 2025-06-02 08:13:28.016372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b504b1e4d844'
down_revision = 'b29d05e24af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_categories_group_id', table_name='categories')
    # op.create_index(op.f('ix_categories_group_id'), 'categories', ['group_id', 'name', 'parent_id'], unique=True)
    # op.drop_index('idx_invitation_code', table_name='group_invitations')
    # op.drop_index('invitation_code', table_name='group_invitations')
    # op.create_unique_constraint(op.f('uq_group_invitations_invitation_code'), 'group_invitations', ['invitation_code'])
    op.add_column('utility_tariffs', sa.Column('subscription_fee', sa.Float(), nullable=True, comment='Абонентська плата'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utility_tariffs', 'subscription_fee')
    # op.drop_constraint(op.f('uq_group_invitations_invitation_code'), 'group_invitations', type_='unique')
    # op.create_index('invitation_code', 'group_invitations', ['invitation_code'], unique=True)
    # op.create_index('idx_invitation_code', 'group_invitations', ['invitation_code'], unique=False)
    # op.drop_index(op.f('ix_categories_group_id'), table_name='categories')
    # op.create_index('idx_categories_group_id', 'categories', ['group_id'], unique=False)
    # ### end Alembic commands ###
