"""Fresh start migration

Revision ID: 846161d0adce
Revises: 
Create Date: 2025-03-04 12:24:56.903061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846161d0adce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_group_association_group_id_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_group_association_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_group_association'))
    )
    with op.batch_alter_table('user_group_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_group_association_user_id'), ['user_id', 'group_id'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_rdate')
        batch_op.create_index(batch_op.f('ix_payments_rdate'), ['rdate', 'user_id', 'category_id', 'mydesc', 'amount', 'is_deleted'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_rdate'))
        batch_op.create_index('ix_payments_rdate', ['rdate', 'user_id', 'category_id', 'mydesc', 'amount', 'is_deleted', 'bank_payment_id'], unique=True)

    with op.batch_alter_table('user_group_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_group_association_user_id'))

    op.drop_table('user_group_association')
    # ### end Alembic commands ###
