"""Auto-generated migration

Revision ID: b85f3776a8f8
Revises: 8e1aab6ddb98
Create Date: 2025-03-04 19:08:44.604333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85f3776a8f8'
down_revision = '8e1aab6ddb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('invitation_code', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=99), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_group_invitations_created_by_users')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_invitations_group_id_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_invitations')),
    sa.UniqueConstraint('invitation_code', name=op.f('uq_group_invitations_invitation_code'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('idx_categories_group_id')
        batch_op.create_index(batch_op.f('ix_categories_group_id'), ['group_id', 'name', 'parent_id'], unique=True)

    with op.batch_alter_table('user_group_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('relation_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group_association', schema=None) as batch_op:
        batch_op.drop_column('joined_at')
        batch_op.drop_column('relation_type')
        batch_op.drop_column('role')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_group_id'))
        batch_op.create_index('idx_categories_group_id', ['group_id'], unique=False)

    op.drop_table('group_invitations')
    # ### end Alembic commands ###
