name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug connection info
        run: |
          echo "Host: ${{ secrets.HOST }}"
          echo "Username: www"
          # Не виводимо сам ключ з міркувань безпеки
          echo "Намагаємось підключитись за допомогою SSH"

      - name: Execute commands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: www
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            cd /home/www/finman/finman_api
            git fetch origin main
            
            COMMIT_MSG=$(git log -1 --pretty=%B origin/main)
            MIGRATION_CHANGES=$(git diff --name-only HEAD origin/main | grep -c "migrations/\|models/")
            
            git pull origin main
            docker compose down
            docker compose up -d --build
            
            sleep 10
            
            # Виконати міграції, якщо є мітка [migrate] або зміни в файлах міграцій чи моделей
            if echo "$COMMIT_MSG" | grep -q "\[migrate\]" || [ "$MIGRATION_CHANGES" -gt 0 ]; then
              echo "Запускаю міграції бази даних..."
              # docker exec finman_api flask db upgrade
            else
              echo "Міграції не потрібні."
            fi